/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trex.sistemabibliotecario.view;

/**
 * @author HP
 */
public class Lectores extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JPanel botones;
    private javax.swing.JButton btnApellido;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnGrado;
    private javax.swing.JButton btnGrupo;
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnNombre;
    private javax.swing.JButton btnTurno;
    private javax.swing.JComboBox<String> cbAsignacion;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbTurno;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tabla_lectores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    /**
     * Creates new form P_lectores
     */
    public Lectores() {
        initComponents();
        Clases.Lectores MT = new Clases.Lectores();
        MT.mostrar(tabla_lectores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox<>();
        btnId = new javax.swing.JButton();
        btnNombre = new javax.swing.JButton();
        btnApellido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbAsignacion = new javax.swing.JComboBox<>();
        btnCategoria = new javax.swing.JButton();
        btnTurno = new javax.swing.JButton();
        btnGrado = new javax.swing.JButton();
        btnGrupo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_lectores = new javax.swing.JTable();
        botones = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(738, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        txtId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtId.setPreferredSize(new java.awt.Dimension(150, 20));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombre.setPreferredSize(new java.awt.Dimension(300, 20));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Apellidos:");

        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtApellido.setPreferredSize(new java.awt.Dimension(300, 20));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Grado:");

        cbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Grado", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto"}));
        cbGrado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbGrado.setMinimumSize(new java.awt.Dimension(150, 20));
        cbGrado.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Grupo:");

        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Grupo", "A", "B"}));
        cbGrupo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbGrupo.setPreferredSize(new java.awt.Dimension(120, 20));

        btnId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnId.setBorder(null);
        btnId.setBorderPainted(false);
        btnId.setContentAreaFilled(false);
        btnId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        btnNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnNombre.setBorder(null);
        btnNombre.setBorderPainted(false);
        btnNombre.setContentAreaFilled(false);
        btnNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        btnApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnApellido.setBorder(null);
        btnApellido.setBorderPainted(false);
        btnApellido.setContentAreaFilled(false);
        btnApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApellidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Turno:");

        cbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Turno", "Matutino", "Vespertino"}));
        cbTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbTurno.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Rol:");

        cbAsignacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Rol", "Alumno", "Profesor"}));
        cbAsignacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnCategoria.setBorder(null);
        btnCategoria.setBorderPainted(false);
        btnCategoria.setContentAreaFilled(false);
        btnCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnTurno.setBorder(null);
        btnTurno.setBorderPainted(false);
        btnTurno.setContentAreaFilled(false);
        btnTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });

        btnGrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnGrado.setBorder(null);
        btnGrado.setBorderPainted(false);
        btnGrado.setContentAreaFilled(false);
        btnGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradoActionPerformed(evt);
            }
        });

        btnGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarPres.png"))); // NOI18N
        btnGrupo.setBorder(null);
        btnGrupo.setBorderPainted(false);
        btnGrupo.setContentAreaFilled(false);
        btnGrupo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoActionPerformed(evt);
            }
        });

        tabla_lectores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tabla_lectores.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        tabla_lectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_lectoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_lectores);

        botones.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nLector.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.setPreferredSize(new java.awt.Dimension(210, 32));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        modificar.setText("Modificar");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setPreferredSize(new java.awt.Dimension(210, 32));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dLector.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setPreferredSize(new java.awt.Dimension(210, 32));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
                botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(botonesLayout.createSequentialGroup()
                                                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        );
        botonesLayout.setVerticalGroup(
                botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(botonesLayout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                           .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                           .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                           .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addContainerGap())
                                      );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(23, 23, 23)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                           .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                                           .addComponent(botones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                           .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                    .addComponent(cbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(cbAsignacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(cbGrupo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                    .addComponent(btnGrupo)
                                                                                                                                                                    .addComponent(btnId)
                                                                                                                                                                    .addComponent(btnCategoria)
                                                                                                                                                                    .addComponent(btnGrado))
                                                                                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                                                                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                                                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(cbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                             .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                    .addComponent(btnApellido)
                                                                                                                                                                    .addComponent(btnTurno)
                                                                                                                                                                    .addComponent(btnNombre))))
                                                    .addGap(39, 39, 39))
                                        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                           .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                                .addComponent(btnId))
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                     .addComponent(jLabel2)
                                                                                                                                                                                                                     .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                     .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                                     .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                                       .addComponent(btnNombre))))
                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                              .addComponent(jLabel7)
                                                                                                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                              .addComponent(cbAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                              .addComponent(btnCategoria)
                                                                                                                                                                                              .addGap(2, 2, 2)))
                                                                                                                                                .addGap(8, 8, 8))
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                              .addComponent(jLabel6)
                                                                                                                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                              .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                       .addComponent(btnApellido))
                                                                                                                                                .addGap(10, 10, 10)))
                                                                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                         .addComponent(btnGrado, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                                                              .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                              .addComponent(btnTurno)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                           .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                  .addComponent(jLabel4)
                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                  .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                           .addComponent(btnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(15, 15, 15)
                                                    .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34))
                                      );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                      .addContainerGap())
                               );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
        Clases.Lectores BIL = new Clases.Lectores();
        BIL.BuscarIdLector(txtId, tabla_lectores);
        BIL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);

    }//GEN-LAST:event_btnIdActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        Clases.Lectores BNL = new Clases.Lectores();
        BNL.BuscarNombreLector(txtNombre, tabla_lectores);
        BNL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApellidoActionPerformed
        Clases.Lectores BAL = new Clases.Lectores();
        BAL.BuscarApellidoLector(txtApellido, tabla_lectores);
        BAL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnApellidoActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        Clases.Lectores BCL = new Clases.Lectores();
        BCL.BuscarCategoriaLector(cbAsignacion, tabla_lectores);
        BCL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        Clases.Lectores BTL = new Clases.Lectores();
        BTL.BuscarTurnoLector(cbTurno, tabla_lectores);
        BTL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnTurnoActionPerformed

    private void btnGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradoActionPerformed
        Clases.Lectores BGL = new Clases.Lectores();
        BGL.BuscarGradoLector(cbGrado, tabla_lectores);
        BGL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnGradoActionPerformed

    private void btnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoActionPerformed
        Clases.Lectores BGL = new Clases.Lectores();
        BGL.BuscarGrupoLector(cbGrupo, tabla_lectores);
        BGL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_btnGrupoActionPerformed

    private void tabla_lectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_lectoresMouseClicked
        Clases.Lectores SL = new Clases.Lectores();
        SL.SeleccionarLector(tabla_lectores, txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_tabla_lectoresMouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        Clases.Lectores AL = new Clases.Lectores();
        AL.agregarLector(txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
        AL.mostrar(tabla_lectores);
        AL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        Clases.Lectores ML = new Clases.Lectores();
        ML.ModificarLector(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
        ML.mostrar(tabla_lectores);
        ML.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Clases.Lectores EL = new Clases.Lectores();
        EL.EliminarLector(txtId);
        EL.mostrar(tabla_lectores);
        EL.Limpiar(txtId, txtNombre, txtApellido, cbGrado, cbGrupo, cbTurno, cbAsignacion);
    }//GEN-LAST:event_eliminarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed
    // End of variables declaration//GEN-END:variables
}
